### ISSUE TITLE
Use Julia LTS release

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#11]
It looks like the latest development work has moved the GSEA.jl package to Julia 1.7.0. 
Unless this is strictly needed for language features, I'd suggest using the latest LTS release instead, which has finally been upgraded to 1.6.4 from 1.0.
(Might be a discussion topic for the meeting today)

**Comment by KwatME** [comment]
![Uploading Screen Shot 2021-12-10 at 17.45.05.png…]()

**Comment by ACastanza** [comment]
This screenshot didn't upload

I did see this quote:

> Almost everyone should be downloading and using the latest stable release of Julia. Great care is taken not to break compatibility with older Julia versions, so older code should continue to work with the latest stable Julia release. You should only be using the long-term support (LTS) version of Julia if you work at an organization where implementing or certifying upgrades is prohibitively expensive and there is no need for new language features or packages. See this description of "Risk Personas" for more detail on who should be using what versions of Julia based on their risk tolerance. See this blog post on Julia's Release Process for more information on different kinds of releases.

On the Julia site, but looking at thier ["Risk Tolerance Personas"](https://julialang.org/blog/2019/08/release-process/#risk_tolerance_personas) documentation, I do think that this would fall into the "Low Risk Tolerance" category if we're developing a production grade application intended to be used by others in their scientific research and bugs in our applications could potentially lead to bad science and retractions.

**Comment by KwatME** [comment]
Let's test a lot, before we plan on this. One step at a time.
