### ISSUE TITLE
run-standard-gsea Identical Statistics and No Plots

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#12]
I ran sarcopenia data (my exact files here: https://drive.google.com/drive/folders/1ynugc7IRbQAWYBnQa9PaqwlEyyjMMUp1?usp=sharing) using the version I've built and installed on MacOS

With the command:

gsea run-standard-gsea /Users/acastanza/GSEA/setting_for_standard_gsea.json /Users/acastanza/GSEA/m2.cp.wikipathways.v0.2.symbols.gmt /Users/acastanza/GSEA/Sarcopenia_bianry_from_cls.tsv /Users/acastanza/Downloads/gse111016_allsamplescounts_htseqcov1_sss_forgeo.sarcopenia.vs.normal_counts_collapsed_to_symbols.tsv /Users/acastanza/GSEA/New_GSEA_test

The only value I changed in the json file was to set to 1000 permutations. 

It seems to finish sucessfully
```
995/1000
  996/1000
  997/1000
  998/1000
  999/1000
  1000/1000
/Users/acastanza/GSEA/New_GSEA_test/set_by_statistic.tsv
Plotting
```

But when I open the set_by_statistic.tsv file (also included in the above drive link), It appears that all the sets have the exact same result statistics

```
Set	Enrichment	P-Value	Q-Value
WP_HOMOLOGOUS_RECOMBINATION	-0.9999999999997834	0.001	0.001
WP_METAPATHWAY_BIOTRANSFORMATION	-0.9999999999997834	0.001	0.001
WP_ACETYLCHOLINE_SYNTHESIS	-0.9999999999997834	0.001	0.001
WP_SREBF_AND_MIR33_IN_CHOLESTEROL_AND_LIPID_HOMEOSTASIS	-0.9999999999997834	0.001	0.001
WP_CALCIUM_REGULATION_IN_THE_CARDIAC_CELL	-0.9999999999997834	0.001	0.001
WP_IRON_HOMEOSTASIS	-0.9999999999997834	0.001	0.001
```

Also, no plots were produced. Any idea what I might've done wrong/what might be going on here?

**Comment by KwatME** [comment]
I tried with your date in `test/runtests.jl` and got a different result

<img width="1188" alt="Screen Shot 2021-12-09 at 21 22 36" src="https://user-images.githubusercontent.com/7741548/145516872-4d378bd2-d908-4ffe-bcec-f2fcc6f2297b.png">

**Comment by ACastanza** [comment]
Hmm. Have you tried running it from the command line directly rather than from inside a notebook?
I'll also try again with the new build that was able to compile on Debian (this issue was opened with the previous MacOS build)

**Comment by KwatME** [comment]
ok

**Comment by KwatME** [comment]
https://github.com/KwatMDPhD/GSEA.jl#test-sarcopenia
