### ISSUE TITLE
InitError(mod=:Blink, error=AssertionError(msg="isfile(f)"))

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#15]
gsea                              Wed Feb  9 10:34:43 2022
┌ Warning: Error requiring `Mux` from `WebIO`
│   exception =
│    LoadError: ArgumentError: Package WebIO does not have JSON in its dependencies:
│    - If you have WebIO checked out for development and have
│      added JSON as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with WebIO
│    Stacktrace:
│      [1] require(into::Module, mod::Symbol)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [2] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [3] include_string(m::Module, txt::String, fname::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [4] top-level scope
│        @ /Users/kwat/.julia/packages/WebIO/Y7bGU/src/WebIO.jl:104
│      [5] (::WebIO.var"#75#87")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [6] macro expansion
│        @ timing.jl:299 [inlined]
│      [7] err(f::Any, listener::Module, modname::String, file::String, line::Any)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:47
│      [8] (::WebIO.var"#74#86")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [9] withpath(f::Any, path::String)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:37
│     [10] (::WebIO.var"#73#85")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│     [11] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:20
│     [12] __init__()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│    in expression starting at /Users/kwat/.julia/packages/WebIO/Y7bGU/src/providers/mux.jl:1
└ @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:51
┌ Warning: Error requiring `WebSockets` from `WebIO`
│   exception =
│    LoadError: ArgumentError: Package WebIO does not have Sockets in its dependencies:
│    - If you have WebIO checked out for development and have
│      added Sockets as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with WebIO
│    Stacktrace:
│      [1] require(into::Module, mod::Symbol)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [2] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [3] include_string(m::Module, txt::String, fname::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [4] top-level scope
│        @ /Users/kwat/.julia/packages/WebIO/Y7bGU/src/WebIO.jl:122
│      [5] (::WebIO.var"#84#96")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [6] macro expansion
│        @ timing.jl:299 [inlined]
│      [7] err(f::Any, listener::Module, modname::String, file::String, line::Any)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:47
│      [8] (::WebIO.var"#83#95")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [9] withpath(f::Any, path::String)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:37
│     [10] (::WebIO.var"#82#94")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│     [11] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:20
│     [12] __init__()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│    in expression starting at /Users/kwat/.julia/packages/WebIO/Y7bGU/src/providers/generic_http.jl:1
└ @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:51
fatal: error thrown and no exception handler available.
InitError(mod=:Blink, error=AssertionError(msg="isfile(f)"))
YY.26_63796.clone_1.clone at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jfptr_YY.26_63797.clone_1 at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
__init___63794.clone_1.clone at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jfptr___init___63795.clone_1 at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_module_run_initializer at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_finish_julia_init at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
julia_init at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_init at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
main at /Applications/gsea/bin/./gsea (unknown line)

**Comment by KwatME** [comment]
I think the first part of this message is a warning. Can you come to https://discord.gg/Q8XyvCfH where we have a live chat about this? @KatharineME is fixing this as we speak I think. Would be nice if we can collaborate there more lively.

**Comment by KwatMDPhD** [comment]
We know how to fix this too. I plan to fix this when we know installation in the current state works. Then doing some more edits to fix warning like this.

**Comment by ACastanza** [comment]
I don't think this is a warning. It results in a fatal error

As a test I tried running:

gsea convert-gct-and-cls /Users/acastanza/github/GSEA.jl/test/data/test_sarcopenia/gse111016_allsamplescounts_htseqcov1_sss_forgeo.sarcopenia.vs.normal_counts_collapsed_to_symbols.gct /Users/acastanza/github/GSEA.jl/test/data/test_sarcopenia/sarcopenia_bianry.cls /Users/acastanza/github/GSEA.jl/test/data/convert_output

from the tutorial and got the same thing:

┌ Warning: Error requiring `Mux` from `WebIO`
│   exception =
│    LoadError: ArgumentError: Package WebIO does not have JSON in its dependencies:
│    - If you have WebIO checked out for development and have
│      added JSON as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with WebIO
│    Stacktrace:
│      [1] require(into::Module, mod::Symbol)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [2] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [3] include_string(m::Module, txt::String, fname::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [4] top-level scope
│        @ /Users/kwat/.julia/packages/WebIO/Y7bGU/src/WebIO.jl:104
│      [5] (::WebIO.var"#75#87")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [6] macro expansion
│        @ timing.jl:299 [inlined]
│      [7] err(f::Any, listener::Module, modname::String, file::String, line::Any)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:47
│      [8] (::WebIO.var"#74#86")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [9] withpath(f::Any, path::String)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:37
│     [10] (::WebIO.var"#73#85")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│     [11] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:20
│     [12] __init__()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│    in expression starting at /Users/kwat/.julia/packages/WebIO/Y7bGU/src/providers/mux.jl:1
└ @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:51
┌ Warning: Error requiring `WebSockets` from `WebIO`
│   exception =
│    LoadError: ArgumentError: Package WebIO does not have Sockets in its dependencies:
│    - If you have WebIO checked out for development and have
│      added Sockets as a dependency but haven't updated your primary
│      environment's manifest file, try `Pkg.resolve()`.
│    - Otherwise you may need to report an issue with WebIO
│    Stacktrace:
│      [1] require(into::Module, mod::Symbol)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [2] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [3] include_string(m::Module, txt::String, fname::String)
│        @ Base /Applications/gsea/lib/julia/sys.dylib:-1
│      [4] top-level scope
│        @ /Users/kwat/.julia/packages/WebIO/Y7bGU/src/WebIO.jl:122
│      [5] (::WebIO.var"#84#96")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [6] macro expansion
│        @ timing.jl:299 [inlined]
│      [7] err(f::Any, listener::Module, modname::String, file::String, line::Any)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:47
│      [8] (::WebIO.var"#83#95")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│      [9] withpath(f::Any, path::String)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:37
│     [10] (::WebIO.var"#82#94")()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│     [11] listenpkg(f::Any, pkg::Base.PkgId)
│        @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:20
│     [12] __init__()
│        @ WebIO /Applications/gsea/lib/julia/sys.dylib:-1
│    in expression starting at /Users/kwat/.julia/packages/WebIO/Y7bGU/src/providers/generic_http.jl:1
└ @ Requires /Users/kwat/.julia/packages/Requires/Z8rfN/src/require.jl:51
fatal: error thrown and no exception handler available.
InitError(mod=:Blink, error=AssertionError(msg="isfile(f)"))
YY.26_63796.clone_1.clone at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jfptr_YY.26_63797.clone_1 at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
__init___63794.clone_1.clone at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jfptr___init___63795.clone_1 at /Applications/gsea/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_module_run_initializer at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_finish_julia_init at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
julia_init at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_init at /Applications/gsea/lib/julia/libjulia-internal.1.7.dylib (unknown line)
main at /Applications/gsea/bin/./gsea (unknown line)

**Comment by KatharineME** [comment]
Hi all, happy we are back at work at this. I am seeing the exact same behavior as you @ACastanza. It is actually two things: a warning related to WebIO, and a fatal error. 

I have an idea of how the WebIO warning might be fixed, which I am trying now. As for the fatal error, I'm still investigating what could be causing it, it could be due to the actual package Blink. 

I'll be posting in the ✨  discord channel ✨ with things I try and how they go.

**Comment by KwatME** [comment]
@Roger-luo

We tried to make "app" and "tarball" with the latest Comonicon. However, we get this error. Any help would be  great.

**Comment by KwatME** [comment]
The final binary works fine in the builder's machine. But if someone downloads the binary, then it fails. You can try running the binary of this repository (1st release).

**Comment by KwatME** [comment]
I hope I'm describing the error accurately @KatharineME . If not please chime in.

**Comment by KatharineME** [comment]
This error seems to arise when Julia isn't installed on the machine where the app binary is being executed. At least, that is the behavior that I have seen so far.

This error was originally documented here https://github.com/JuliaLang/PackageCompiler.jl/issues/650. I am in the process of trying the suggested fix there.

**Comment by ACastanza** [comment]
I was under the impression that we were moving away from julia?

**Comment by KwatME** [comment]
Fixed!

We just need to make stable, easy-to-maintain, cross-platform `gsea` .
