### ISSUE TITLE
Rename arguments

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#18]
> Run standard GSEA
> 
> Args
> 
>   \<js>
>   \<se>
>   \<tst>
>   \<tsd>
>   \<ou>                                          output directory
> 

This and other commands need a plain text description of what part of the data each parameter is supposed to accept, without it we just have to guess which makes it difficult to tell if we're doing something wrong or the code is actually erroring.

**Comment by KwatME** [comment]
Will change these to full text as soon as binary works.

Can you try the 0.3.0?
