### ISSUE TITLE
v0.3 ERROR: MethodError: Cannot `convert` an object of type InlineStrings.String31 to an object of type Bool

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#19]
cmd: gsea run-standard-gsea /Users/acastanza/test/data/convert_output/c2.cp.wikipathways.v7.4.symbols.js /Users/acastanza/test/data/setting_for_standard_gsea.json /Users/acastanza/test/data/convert_output/score.gene_by_sample.tsv /Users/acastanza/test/data/convert_output/score.target_by_sample.tsv /Users/acastanza/test/data/sarc_out_test

```
ERROR: MethodError: Cannot `convert` an object of type InlineStrings.String31 to an object of type Bool
Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer at pointer.jl:23
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:262
  convert(::Type{T}, ::AbstractChar) where T<:Number at char.jl:185
  ...
Stacktrace:
 [1] setindex!(A::Vector{Bool}, x::InlineStrings.String31, i1::Int64)
   @ Base ./array.jl:903
 [2] fill_bitarray_from_itr!(B::BitVector, itr::DataFrames.DataFrameRow{DataFrames.DataFrame, DataFrames.Index})
   @ Base /Applications/gsea/lib/julia/sys.dylib:-1
 [3] gen_bitarray(#unused#::Base.HasLength, itr::DataFrames.DataFrameRow{DataFrames.DataFrame, DataFrames.Index})
   @ Base /Applications/gsea/lib/julia/sys.dylib:-1
 [4] run_standard_gsea(js::String, se::String, tst::String, tsd::String, ou::String)
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [5] command_main(ARGS::Vector{String})
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [6] julia_main()
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [7] top-level scope
   @ none:1

```
Input files that were successfully produced with the built-in convert commands (.txt extension added to allow github upload):
[score.target_by_sample.tsv.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8038696/score.target_by_sample.tsv.txt)
[c2.cp.wikipathways.v7.4.symbols.js.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8038690/c2.cp.wikipathways.v7.4.symbols.js.txt)
[score.gene_by_sample.tsv.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8038691/score.gene_by_sample.tsv.txt)

settings json:
[setting_for_standard_gsea.json.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8038697/setting_for_standard_gsea.json.txt)

**Comment by KwatME** [comment]
`.js` as in javascript?

**Comment by KwatME** [comment]
After renaming the .js to .json i was able to run this. I hope the results are good. Let me know.

**Comment by KwatME** [comment]
We definitely need to improve error messages.

**Comment by KwatME** [comment]
~/Downloads/gsea/bin/gsea run-standard-gsea setting_for_standard_gsea.json c2.cp.wikipathways.v7.4.symbols.json score.target_by_sample.tsv score.gene_by_sample.tsv .

**Comment by KwatME** [comment]
<img width="906" alt="Screen Shot 2022-02-10 at 00 08 11" src="https://user-images.githubusercontent.com/7741548/153355614-b5eb513c-3a10-4f30-a720-829c2035c729.png">

**Comment by KwatME** [comment]
<img width="909" alt="Screen Shot 2022-02-10 at 00 08 34" src="https://user-images.githubusercontent.com/7741548/153355658-27adb9ad-72ed-4eef-a1cc-1832ef79bee4.png">

**Comment by ACastanza** [comment]
```
gsea run-standard-gsea /Users/acastanza/test/data/convert_output/c2.cp.wikipathways.v7.4.symbols.json /Users/acastanza/test/data/setting_for_standard_gsea.json /Users/acastanza/test/data/convert_output/score.target_by_sample.tsv /Users/acastanza/test/data/convert_output/score.gene_by_sample.tsv .
ERROR: KeyError: key "mi" not found
Stacktrace:
 [1] read_set(pa::String, ke_ar::Dict{String, Any})
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [2] run_standard_gsea(js::String, se::String, tst::String, tsd::String, ou::String)
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [3] command_main(ARGS::Vector{String})
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [4] julia_main()
   @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
 [5] top-level scope
   @ none:1
```

**Comment by ACastanza** [comment]
IT RUNS!

**Comment by ACastanza** [comment]
I saw in the discord that it looks like you've disabled plotting (temporarily?) but it computes scores!

**Comment by KwatME** [comment]
Yea PlotlyJS causes some issues because it uses `electron` and exponentially increases the dependencies. So I have to write my own plotting library that directly accesses Plotly without all the heavy dependencies.

**Comment by KwatME** [comment]
We just have to 1) add plot 2) build for ubuntu 3) improve args, docs, and 4) use a lot
