### ISSUE TITLE
Accept string `.cls`

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#27]
When specifying the assignment of phenotypes to samples in the third line of the CLS file, the gsea convert-gct-and-cls command appears to only allow numeric values and not strings. If supplying strings (see attached cls file) the following error is recieved:
 
> ERROR: ArgumentError: cannot parse "Normal" as Float64
> Stacktrace:
>  [1] _parse_failure(T::Type, s::SubString{String}, startpos::Int64, endpos::Int64) (repeats 2 times)
>    @ Base ./parse.jl:373
>  [2] convert_gct_and_cls(gct::String, cls::String, output_directory::String)
>    @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
>  [3] command_main(ARGS::Vector{String})
>    @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
>  [4] julia_main()
>    @ GSEA /Applications/gsea/lib/julia/sys.dylib:-1
>  [5] top-level scope
>    @ none:1

File (.txt extension appended for GitHub upload): 
[sarcopenia.cls.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8050896/sarcopenia.cls.txt)

**Comment by KwatME** [comment]
We can make a universal converter later. This adds a lot of code for doing non-`gsea` things. Let's focus on the math and main features before we slow down with conversion. Let's use `.tsv` for now. I promise to make a stand-alone converter.

**Comment by davideby** [comment]
@KwatMDPhD I agree.  Focus on the math & computation right now.  We already have CLS parsers in Python, R, Java and can just make converters from those.

I'd say, just accept some kind of two-class phenotype specification vector and some kind of continuous phenotype specification vector and we'll have the outside code wrangle CLS into the right format.

**Comment by KwatME** [comment]
I'll delegate conversion to your team then.
