### ISSUE TITLE
Remove `convert*` (and accept `.tsv`; later there can be a converter from other file formats to `.tsv`)

### ISSUE THREAD

**Issue by KwatME** [GSEA-MSigDB/GSEA.jl#28]

**Comment by ACastanza** [comment]
If you're going to unify the convert commands, it'd be nice if it could also run independently on each file type. Like, if someone has already converted their data but then wants to convert a different collection of gene sets, or use different phenotype assignments, it'd be nice if the convert cls or convert gmt could run independently without needing to provide all of gct/gmt/cls every time.

**Comment by KwatME** [comment]
<img width="1110" alt="Screen Shot 2022-02-11 at 15 38 57" src="https://user-images.githubusercontent.com/7741548/153680302-7df3da20-462e-4159-96f1-09d90dc52e7d.png">
 On it ;)

**Comment by ACastanza** [comment]
Great! GMX support might also be nice, it's the same as GMT except columns instead of rows!
