### ISSUE TITLE
Make cli gif a static image

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#3]
It would be great if we could get a static image instead of a gif of the cli example. The gif loops too quickly to see what the cli help actually looks like and it'd be simpler to just have a static image.

**Comment by KwatME** [comment]
Got it. Will do.

**Comment by ACastanza** [comment]
Thanks, not a big deal, I was able to get the information from going to the function code, it's just a pet peeve about how this kind of thing is presented.

**Comment by KwatME** [comment]
Removed .gif for now. When we stabilize the interface, let's make a nice pictorial.
