### ISSUE TITLE
Match FDR with desktop

### ISSUE THREAD

**Issue by KwatME** [GSEA-MSigDB/GSEA.jl#33]

**Comment by ACastanza** [comment]
For reference, the FDR calculation in GSEA's R codebase: https://github.com/GSEA-MSigDB/GSEA_R/blob/b49beee596ec188deaf62cb3d40d1c7c006af347/R/GSEA.R#L821

**Comment by ACastanza** [comment]
The original FDR calculation:

>  for (k in 1:Ng) {
>   NES[k] <- Obs.ES.norm.sorted[k]
>   ES.value <- NES[k]
>   count.col <- vector(length = nperm, mode = "numeric")
>   obs.count.col <- vector(length = nperm, mode = "numeric")
>   for (i in 1:nperm) {
>    phi.vec <- phi.norm[, i]
>    obs.phi.vec <- obs.phi.norm[, i]
>    if (ES.value >= 0) {
>     count.col.norm <- sum(phi.vec >= 0)
>     obs.count.col.norm <- sum(obs.phi.vec >= 0)
>     count.col[i] <- ifelse(count.col.norm > 0, sum(phi.vec >= ES.value)/count.col.norm, 
>       0)
>     obs.count.col[i] <- ifelse(obs.count.col.norm > 0, sum(obs.phi.vec >= 
>       ES.value)/obs.count.col.norm, 0)
>    } else {
>     count.col.norm <- sum(phi.vec < 0)
>     obs.count.col.norm <- sum(obs.phi.vec < 0)
>     count.col[i] <- ifelse(count.col.norm > 0, sum(phi.vec <= ES.value)/count.col.norm, 
>       0)
>     obs.count.col[i] <- ifelse(obs.count.col.norm > 0, sum(obs.phi.vec <= 
>       ES.value)/obs.count.col.norm, 0)
>    }
>   }
>   phi.norm.mean[k] <- mean(count.col)
>   obs.phi.norm.mean[k] <- mean(obs.count.col)
>   FDR.mean[k] <- ifelse(phi.norm.mean[k]/obs.phi.norm.mean[k] < 1, phi.norm.mean[k]/obs.phi.norm.mean[k], 
>    1)
>  }

**Comment by ACastanza** [comment]
Trying to translate it into plain language:
(NES[geneset] would be the NES for the given gene set)

> for (geneset in 1:number_of_genesets) { 
>   for (i in 1:nperm) {
>    Normalized_Permuted_Enrichment_Scores <- Normalized_Permuted_Enrichment_Scores[, i]
>    if (NES[gene_set] >= 0) {
>     Normalized_Permuted_Enrichment_Scores_that_match_the_sign_of_NES[geneset] <- sum(Normalized_Permuted_Enrichment_Scores >= 0)
>     number_of_real_NES_that_match_the_sign_of_NES[geneset] <- sum(all_real_NES >= 0)
>     count.col[i] <- ifelse(Normalized_Permuted_Enrichment_Scores_that_match_the_sign_of_NES[geneset] > 0, sum(Normalized_Permuted_Enrichment_Scores >= NES[gene_set])/Normalized_Permuted_Enrichment_Scores_that_match_the_sign_of_NES[geneset], 
>       0)
>     obs.count.col[i] <- ifelse(number_of_real_NES_that_match_the_sign_of_NES[geneset] > 0, sum(all_real_NES >= 
>       NES[gene_set])/number_of_real_NES_that_match_the_sign_of_NES[geneset], 0)
>    } else {
>     Normalized_Permuted_Enrichment_Scores_that_match_the_sign_of_NES[geneset] <- sum(Normalized_Permuted_Enrichment_Scores < 0)
>     number_of_real_NES_that_match_the_sign_of_NES[geneset] <- sum(all_real_NES < 0)
>     count.col[i] <- ifelse(Normalized_Permuted_Enrichment_Scores_that_match_the_sign_of_NES[geneset] > 0, sum(Normalized_Permuted_Enrichment_Scores <= NES[gene_set])/Normalized_Permuted_Enrichment_Scores_that_match_the_sign_of_NES[geneset], 
>       0)
>     obs.count.col[i] <- ifelse(number_of_real_NES_that_match_the_sign_of_NES[geneset] > 0, sum(all_real_NES <= 
>       NES[gene_set])/number_of_real_NES_that_match_the_sign_of_NES[geneset], 0)
>    }
>   }
>   phi.norm.mean[geneset] <- mean(count.col)
>   obs.phi.norm.mean[geneset] <- mean(obs.count.col)
> 
>   FDR.mean[geneset] <- ifelse(phi.norm.mean[geneset]/obs.phi.norm.mean[geneset] < 1, phi.norm.mean[geneset]/obs.phi.norm.mean[geneset], 
>    1)
>  }
> 

An important piece is that the calculations are being done on a matrix of number of sets (rows) by number of permutations (columns) for both the permuted scores and real scores. So the real score matrix also has nperm columns it's just the same values in every column. Whereas the permutation score matrix has the results of each unique permutation in each column
