### ISSUE TITLE
Plotting: Flip Horizontal

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#37]
Horizontal flip of plots to match orientation of desktop GSEA
Current
![newplot](https://user-images.githubusercontent.com/26012303/155228364-dbc94082-3140-4e13-ab47-edc1c406af0b.png)
:
![newplot(1)](https://user-images.githubusercontent.com/26012303/155228368-d929f3c7-1ace-46a3-a9a1-18fbda83de86.png)

Should be:
![newplot](https://user-images.githubusercontent.com/26012303/155228427-b448d8b3-efb9-4482-a68e-c4f73b906efa.png)
![newplot(1)](https://user-images.githubusercontent.com/26012303/155228435-524e6766-8ebf-4e6f-89e6-e649c9842c06.png)

**Comment by KwatME** [comment]
Let's do this at the very end. This issue will be part of the final flip issue.
