### ISSUE TITLE
Plotting: Saving plot from the HTML as PNG uses generic name

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#38]
Not sure if this is fixable by default, but when saving a plot from the HTML page as a png using the built in save option it uses the generic name "newplot.png" by default. It'd be nice if when saving the plot as png it automatically used the gene set name.png to prevent users needing to manually rename each plot on save.

**Comment by KwatME** [comment]
Can't fix this.
