### ISSUE TITLE
Plotting: Change Hover Marker Color

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#39]
By default, when hovering over the plot it highlights the set gene at that point (great!) however, the hover line color is white, matching the background. This may be a darkmode issue (unconfirmed), but a midtone like a grey might be preferred. 

Current behavior:
<img width="350" alt="Screen Shot 2022-02-22 at 2 16 01 PM" src="https://user-images.githubusercontent.com/26012303/155228769-f61f1c7d-ae32-4d52-85c3-f8357a076bdb.png">

**Comment by KwatME** [comment]
Great catch

**Comment by ACastanza** [comment]
Seems like it's still doing a white hover line in some cases but not all, not sure why and when, these are the same plot from the same run

![Screen Shot 2022-03-17 at 1 50 34 PM](https://user-images.githubusercontent.com/26012303/158893054-c0d1209c-ed7c-48e3-807d-e21b36915bd0.png)

![Screen Shot 2022-03-17 at 1 50 28 PM](https://user-images.githubusercontent.com/26012303/158893057-a8cdca06-39fc-4d0a-90af-c87106657e9d.png)

**Comment by KwatME** [comment]
Can't reproduce this. I don't know what is going on.

**Comment by KwatME** [comment]
I updated a few things and try them out. If this shows up again, feel free to reopen.
