### ISSUE TITLE
Statistics: Sorting of tsvs appears Negative to Positive, reverse would be preferred

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#41]
Both score.gene_x_metric.tsv and float.set_x_statistic.tsv seem to be sorted negative to positive instead of positive to negative, ideally we would have this reversed just as a convention.

**Comment by KwatME** [comment]
Let's fix all direction at the end. By default, things are increasing in natural direction. Plot has the same issue which we can fix all at the end.
