### ISSUE TITLE
Write out additional dict containing running enrichment score data for all sets

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#44]
In order to produce some of the results tables users currently expect and reproduce features like leading edge analysis, we need to produce a parseable file that contains additional scoring information from the enrichment calculation. We'd basically want it to contain everything you'd need to produce the enrichment plot but for all sets.

**Comment by KwatME** [comment]
I just realized that the .html plot has these values in it! It has everything!

**Comment by KwatME** [comment]
Can you see if you can use the values in .html? If this is not doable, I can save with some speed sacrifice. Either is fine. Maybe I can make an extractor from the .html.

**Comment by ACastanza** [comment]
Hadn't realized this got closed, I'll take a look at parsing this out from the html blob

**Comment by ACastanza** [comment]
So, I was able to parse out the data for the ones with plots pretty easily, which is enough to build the reports, but I think we do still need to make a change here since for the complete leading edge analysis sometimes users need to go deeper than just the sets we've chosen to plot. If its possible to dump out the kind of underlying data that's in this html file but for all sets as a combined json file that would be ideal.

**Comment by ACastanza** [comment]
Turns out I was using the old version of the plots before you reworked them, the new version is **much much** harder to parse out the content from.
