### ISSUE TITLE
Write out additional dict containing permuted enrichment scores for all sets

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#45]
Another output we produce is a plot of the enrichment score null distribution. In order to reproduce this plot, an additional output containing the permuted es scores for each set would be needed.

**Comment by KwatME** [comment]
set_x_random_x_enrichment.tsv is now saved :)

**Comment by ACastanza** [comment]
This appears to work correctly in gene set permutation mode, but in phenotype permutation mode the permuted score appears identical for every column
[set_x_random_x_enrichment_sample_perm.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8401077/set_x_random_x_enrichment_sample_perm.txt)
[set_x_random_x_enrichment_set_perm_run_through_preranked.txt](https://github.com/KwatMDPhD/GSEA.jl/files/8401078/set_x_random_x_enrichment_set_perm_run_through_preranked.txt)

**Comment by KwatME** [comment]
Got it. Will fix.

**Comment by KwatME** [comment]
Fixed. Will be in the next release scheduled for this evening.
