### ISSUE TITLE
Plotting: Long gene set names not scaling properly in plot titles

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#49]
![Screenshot 2022-03-09 233718](https://user-images.githubusercontent.com/26012303/157611948-ffaff2c9-fe4d-49d7-b5a4-1f6e8848e1bf.png)

Full title should be: REACTOME_ESTROGEN_DEPENDENT_NUCLEAR_EVENTS_DOWNSTREAM_OF_ESR_MEMBRANE_SIGNALING

Scaling font sizes reasonably is going to be a little tricky, but some scaling combined with maybe making the plots a little bigger might help?

**Comment by ACastanza** [comment]
Same plot from the previous 0.7x version doesn't show this issue: 
![newplot](https://user-images.githubusercontent.com/26012303/157614764-1606a1aa-a7cc-4919-805b-f6f559318da6.png)

**Comment by ACastanza** [comment]
Looks like this might not be working in the 0.9.0 build

**Comment by KwatME** [comment]
Does it trim the name? Title wrapping was more involved than expected, so I trimmed it to 32 characters. It's rare that someone uses the gene set name as is, so I thought this may be practical and robust.

**Comment by ACastanza** [comment]
It does trim the name, the wrapping in the original version was better. It is not "rare that someone uses the gene set name as it" that is in fact what happens most of the time.

**Comment by KwatME** [comment]
DOnel.
