### ISSUE TITLE
0.11.3 Fails to Build

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#61]
>  => ERROR [gsea_build 5/6] RUN cd GSEA.jl && julia --project --eval 'using Pkg; Pkg.instantiate()'                 4.5s
> ------
>  > [gsea_build 5/6] RUN cd GSEA.jl && julia --project --eval 'using Pkg; Pkg.instantiate()':
> #11 1.162   Installing known registries into `~/.julia`
> #11 3.425 ERROR: Did not find path `/Users/kwat/Downloads/PackageCompiler.jl` for `PackageCompiler [9b87118b]`
> #11 4.002 Stacktrace:
> #11 4.002  [1] pkgerror(msg::String)
> #11 4.261    @ Pkg.Types /usr/local/julia/share/julia/stdlib/v1.7/Pkg/src/Types.jl:68
> #11 4.365  [2] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
> #11 4.409    @ Pkg.API /usr/local/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:1489
> #11 4.409  [3] instantiate
> #11 4.409    @ /usr/local/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:1422 [inlined]
> #11 4.409  [4] #instantiate#276
> #11 4.409    @ /usr/local/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:1418 [inlined]
> #11 4.409  [5] instantiate()
> #11 4.409    @ Pkg.API /usr/local/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:1418
> #11 4.410  [6] top-level scope
> #11 4.410    @ none:1
> ------
> executor failed running [/bin/sh -c cd GSEA.jl && julia --project --eval 'using Pkg; Pkg.instantiate()']: exit code: 1

Is there a change to the command used to build? I know you were tweaking packagecompiler stuff.

**Comment by KwatME** [comment]
Try 0.11.4.

**Comment by KwatME** [comment]
https://github.com/KwatMDPhD/GSEA.jl/releases/tag/0.11.4

**Comment by ACastanza** [comment]
0.11.4 builds!
