### ISSUE TITLE
data-rank fails with error

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#62]
> ERROR: MethodError: no method matching isnan(::InlineStrings.String31)
> Closest candidates are:
>   isnan(!Matched::Complex) at complex.jl:147
>   isnan(!Matched::DualNumbers.Dual) at ~/.julia/packages/DualNumbers/5knFX/src/dual.jl:52
>   isnan(!Matched::Union{GeometryBasics.AbstractPoint, GeometryBasics.Vec}) at ~/.julia/packages/GeometryBasics/5Sb5M/src/fixed_arrays.jl:126
>   ...
> Stacktrace:
>   [1] (::OnePiece.data_frame.var"#1#2"{InlineStrings.String31})(is::typeof(isnan))
>     @ OnePiece.data_frame ./none:0
>   [2] iterate
>     @ ./generator.jl:47 [inlined]
>   [3] _any(f::typeof(identity), itr::Base.Generator{Vector{Function}, OnePiece.data_frame.var"#1#2"{InlineStrings.String31}}, #unused#::Colon)
>     @ Base ./reduce.jl:1114
>   [4] any
>     @ ./reduce.jl:1105 [inlined]
>   [5] any(itr::Base.Generator{Vector{Function}, OnePiece.data_frame.var"#1#2"{InlineStrings.String31}})
>     @ Base ./reduce.jl:1031
>   [6] error_bad(da::DataFrames.DataFrame)
>     @ OnePiece.data_frame ~/.julia/packages/OnePiece/zpgBM/src/data_frame/error_bad.jl:23
>   [7] score_set(fe_x_sa_x_sc::DataFrames.DataFrame, se_fe_::Dict{String, Any}; al::String, ex::Float64, n_jo::Int64)
>     @ OnePiece.feature_set_enrichment ~/.julia/packages/OnePiece/zpgBM/src/feature_set_enrichment/score_set.jl:142
>   [8] data_rank(setting_json::String, gene_x_sample_x_score_tsv::String, set_genes_json::String, output_directory::String)
>     @ GSEA /GSEA.jl/src/data_rank.jl:27
>   [9] command_main(ARGS::Vector{String})
>     @ GSEA ~/.julia/packages/Comonicon/RerN0/src/codegen/julia.jl:322
>  [10] command_main
>     @ ~/.julia/packages/Comonicon/RerN0/src/codegen/julia.jl:88 [inlined]
>  [11] julia_main()
>     @ GSEA ~/.julia/packages/Comonicon/RerN0/src/frontend/cast.jl:478
>  [12] top-level scope
>     @ none:1
> Traceback (most recent call last):
>   File "/opt/gpbeta_2/gp_home/taskLib/ssGSEA2.1.1.2547/run.ssgsea2.py", line 204, in <module>
>     main()
>   File "/opt/gpbeta_2/gp_home/taskLib/ssGSEA2.1.1.2547/run.ssgsea2.py", line 184, in main
>     subprocess.check_output(['gsea', 'data-rank', 'input/gsea_settings.json',
>   File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['gsea', 'data-rank', 'input/gsea_settings.json', 'input/gene_by_sample.tsv', 'input/filtered_set_to_genes.json', '/opt/gpbeta_2/gp_home/jobResults/88957']' returned non-zero exit status 1.
> 

Input files available in the /input/ folder in the job results here: https://beta.genepattern.org/gp/pages/index.jsf?jobid=88957&openVisualizers=true&openNewWindow=false

**Comment by ACastanza** [comment]
This might be an error in adopting the changes you made to various parameters, working on it now.

**Comment by KwatME** [comment]
<img width="729" alt="Screen Shot 2022-08-10 at 12 54 44" src="https://user-images.githubusercontent.com/7741548/183994466-9f09daa0-fd40-47c7-8940-68eda9c578cb.png">

It looks like the `.tsv`'s 2nd column is `Gene.Symbol`, which may have been inherited from `.gct`. Can you try removing this column?

**Comment by KwatME** [comment]
I did 2 things to make it work.

1) Removed the 2nd column.
2) Set `algorithm` to be `ks`.

[bug_1.zip](https://github.com/KwatMDPhD/GSEA.jl/files/9303252/bug_1.zip)

**Comment by ACastanza** [comment]
Huh, strange, I didn't change anything in the code for creating that tsv from what was used in the previous version. I'll make those changes, thanks!

**Comment by KwatME** [comment]
Thanks for the bug reports :)

Keep. It. Coming.

Let's make this tool simple, robust, and liked.
