### ISSUE TITLE
Use good .html format

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#63]
At some point between the 0.9.1 and 0.11.3 release the structure of the HTML underlying the enrichment plot page was changed. This is the third time that this HTML has been substantially changed. Please revert this change to the prior 0.9.1 structure. Every time this changes I have to rewrite the parser that extracts things like the leading edge information and produces the complete results pages. This version of the plot contains some issue that I can't find an easy way to work around.

**Comment by ACastanza** [comment]
~~Nevermind, I think I figured out a way to parse this new version after all.~~

**Comment by ACastanza** [comment]
Nope, I can't get this to work, something that changed here is messing up all of the parsing logic I was using.

**Comment by ACastanza** [comment]
I think the issue is the indentations in the "Plotly.newPlot() function, and the change that dropped the spaces in the ", " separators between subdicts.

**Comment by KwatME** [comment]
```
function plot(data, layout = Dict(); config = Dict(), ou = "")

    layout0 = Dict("hovermode" => "closest")

    config0 = Dict(
        "modebarbuttonstoremove" => ["select", "lasso", "resetscale"],
        "displaylogo" => false,
        "responsive" => true,
        "editable" => false,
    )

    di = "plot"

    sr = ["https://cdn.plot.ly/plotly-latest.min.js"]

    sc = """
    Plotly.newPlot(

        \"$di\",

        $(JSON3.write(data)),

        $(JSON3.write(OnePiece.dict.merge(layout0, layout))),

        $(JSON3.write(OnePiece.dict.merge(config0, config))),

    )
    """

    OnePiece.html.make(di, sr, sc, ou)

end
```

Maybe there are spaces now?

When parsing HTML, people often use some kind of cleaner (prettier) to ensure the structure. Can we try that?

**Comment by KwatME** [comment]
Can we try running `npx prettier --write` before each parsing to make sure the parser gets the same structure no matter what?

**Comment by KwatME** [comment]
https://prettier.io/docs/en/install.html

**Comment by ACastanza** [comment]
I really don't want to add yet another package to this module. Please just revert the plot structure to how it was before so I could manually parse out the information I needed.

**Comment by KwatME** [comment]
I don't want to establish a bad .html file format just because we had it before. Let me add `prettier` on my end so every .html is pretty and consistent.

**Comment by ACastanza** [comment]
[descartes_fetal_cerebellum_slc24a4_pex5l_positive_cells.txt](https://github.com/KwatMDPhD/GSEA.jl/files/9304118/descartes_fetal_cerebellum_slc24a4_pex5l_positive_cells.txt)
If you take this file as an example (rename to .html and open in a browser's view source)

I just need to be able to parse the information on line 10 here into a python dictionary
<img width="1307" alt="Screen Shot 2022-08-10 at 2 22 22 PM" src="https://user-images.githubusercontent.com/26012303/184022694-7a802896-8664-42a6-9ddd-dd3873918aaa.png">

All I was doing was reading the html in as text, splitting the lines to get the dict I needed, then forcing python to read it as a dict as-is, with ast.literal_eval, the problem seems to be that the way it is indented is breaking the ast function.

The exact code I was using to parse the _old_ version was
`content = ast.literal_eval(html_plot_page.split(
        "\n")[4].split(', ')[1].strip(']['))`

No matter how I try to tweak things for the new structure, I keep getting "IndentationError: unexpected indent"

**Comment by ACastanza** [comment]
Oh! I actually _did_ figure out a way to resolve the indentation issue!

**Comment by ACastanza** [comment]
I was able to get it to parse, so maybe it's best if we just leave this alone after all.

**Comment by KwatME** [comment]
Bravo🖖

**Comment by KwatME** [comment]
But you do bring a good point about how all output `.html`s should be standardized... If this issue comes up again, then I'll add `prettier` on my end and make all `.html` pretty.
