### ISSUE TITLE
Logic error in selecting which sets to plot

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#64]
~~It appears that the sets selected for plotting on the positive and negative sides are (independently) off by one. I.e. only the top 19 and bottom 19 plots are being produced when `"number_of_extreme_gene_sets_to_plot": 20,` was set in the json.~~

Additionally, if there are fewer than 20 (19) sets on one "side" of the enrichment (i.e. there are only 10 sets enriched in the negative phenotype) then the remainder will be plotted selected from the "bottom" sets of the positive phenotype.

See here where three sets at the very bottom of this list are being plotted:

![Screen Shot 2022-08-11 at 1 30 06 PM](https://user-images.githubusercontent.com/26012303/184236573-c3ad53d0-7f46-44eb-990b-16ba5abe2cd3.png)

This is occurring because there are only 16 sets enriched on the other side of the distribution:

![Screen Shot 2022-08-11 at 1 38 43 PM](https://user-images.githubusercontent.com/26012303/184237964-1e5abebe-18a4-496c-974b-c9b3b2a85715.png)

(The presence of the "Details" link indicates that there is a plot present for this set)

**Comment by KwatME** [comment]
If you open those `Details...`, do the plot title match the gene-set name? If not, then this could be downstream error. Meanwhile, I'm looking into this upstream.

**Comment by ACastanza** [comment]
Yes, the plot titles match the set names in the table

**Comment by KwatME** [comment]
I checked the setting number and the number of plots in `plot/` and they match for all cases. I don't know what is going on here.

**Comment by ACastanza** [comment]
Okay, this is odd, somehow HALLMARK_E2F_TARGETS, and HALLMARK_IL6_JAK_STAT3_SIGNALING were removed from my results table. So at least that part of this is on me. The wrapping around to plot the bottom sets of another phenotype is the only issue then.

**Comment by KwatME** [comment]
Can you try deleting the output and try again? `gsea` does not delete.

**Comment by ACastanza** [comment]
Huh? These are clean runs in a clean docker container every time. The correct numebr of plots are being created, but if there aren't N>nsets to plot on one side of the distribution it's wrapping around.

**Comment by KwatME** [comment]
Ah I see. I don't think I take into account the "side" now. I just pick the top and bottom. I can fix this. I know what to do. By the way can you check discord?

**Comment by ACastanza** [comment]
The fix for those sets being dropped ended up being simple, I was changing from 0 based to 1 based indexing incorrectly in creating the results html table

**Comment by KwatME** [comment]
This should also solve #65, or vice versa.
