### ISSUE TITLE
Check the number of sets for plotting and more

### ISSUE THREAD

**Issue by KwatME** [GSEA-MSigDB/GSEA.jl#65]
@ACastanza

**Comment by KwatME** [comment]
I'm going to error or warn if a user plans to plot the top 20 gene sets but the user only provides less-than-20 sets.

**Comment by ACastanza** [comment]
I'd go warn if at all. Doesn't seem reasonable to straight up fail the job purely because it couldn't plot more sets than exist. It's one of those parameters that shouldn't really matter for most users and we shouldn't make them need to think about it unless they know they need to.
