### ISSUE TITLE
Make the new algorithm computation faster

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/GSEA.jl#67]
Running the GSEA.jl code with the K-S statistic for a dataset with 10,000 gene set permutations for 5020 gene sets runs in about 1 hour 15 minutes, this is inline with GSEA Desktop's runtime.
However running the same data with the CIDAC statistic showed a predicted runtime of ~60 hours (when the job timed out at 8 hours, it still showed 52 hours remaining).

**Comment by ACastanza** [comment]
I just noticed that this is time blowup is already happening in small jobs and with phenotype permutation:
KS 1000 phenotype perms 30 seconds: https://beta.genepattern.org/gp/jobResults/89374/stderr.txt
CIDAC 1000 phenotype perms 16 minutes: https://beta.genepattern.org/gp/jobResults/89371/stderr.txt
jobs are otherwise identical just old vs new algorithm

**Comment by KwatME** [comment]
Thanks for the benchmark. We are going to be revisiting the algorithm in October. When the exact algorithm is decided once for all, I plan to optimize the speed.
