### ISSUE TITLE
Write instructions for `julia` interface.

### ISSUE THREAD

**Issue by yang-dongxu** [GSEA-MSigDB/GSEA.jl#76]
**Issue Description**:
The current module supports GSEA analysis in cmdline, which is useful in many cases. However, there are certain circumstances where it would be more convenient to use the module functions directly in Julia. Unfortunately, the readme does not provide any instructions on how to do this.

**Additional Information**:
I would appreciate if someone could provide guidance or documentation on utilizing the module functions in Julia directly. This would greatly enhance the usability of the module in various scenarios. Thank you!

**Comment by KwatME** [comment]
Will do 👍

**Comment by KwatME** [comment]
I added some basic documentation for using `GSEA` in `julia`. Please let me know if you want more specifics.
