### ISSUE TITLE
Rename to GSEA2.jl.

### ISSUE THREAD

**Issue by KwatME** [GSEA-MSigDB/GSEA.jl#82]
In julia, package names are title cased. Without following this convention, this package won't be registered.

https://julialang.org/contribute/developing_package/

**Comment by helgathorv** [comment]
Does the repo name have to be the same as the package name? 
If so, I can change it to upper case - I used lower case because that's the norm for all our other repos. 
But note also the "2" in the new name - that I do want to keep.

**Comment by KwatME** [comment]
1 repo = 1 package = TitleCase.jl (GSEA2.jl) 👈 should work.

I used lowercase before adopting julia. This convention was new to me as well.

**Comment by helgathorv** [comment]
Done
