### ISSUE TITLE
Match the 1 liners.

### ISSUE THREAD

**Issue by KwatME** [GSEA-MSigDB/GSEA.jl#83]
<img width="493" alt="Screenshot 2024-08-28 at 11 27 45" src="https://github.com/user-attachments/assets/526685f3-bd1a-4d05-8278-100f0a39d0f5">

<img width="335" alt="Screenshot 2024-08-28 at 11 27 53" src="https://github.com/user-attachments/assets/647d3ad3-4d83-47fa-824a-11ac57db9f1e">

Missing 1 emoji 🙈

You can even select the line from README.md - including the emoji - and then paste it to the description.

**Comment by helgathorv** [comment]
Done
